eshop/api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views


app_name = "api"
urlpatterns = [
    # Token
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    # AttributeName Objects
    path("attributename/", views.AttributeNameCreateAPIView.as_view()),
    path(
        "attributename/<int:pk>/", views.AttributeNameGetUpdateDestroyAPIView.as_view()
    ),
    path("attributenames/", views.AttributeNameListAPIView.as_view()),
    # AttributeValue Objects
    path("attributevalue/", views.AttributeValueCreateAPIView.as_view()),
    path(
        "attributevalue/<int:pk>/",
        views.AttributeValueGetUpdateDestroyAPIView.as_view(),
    ),
    path("attributevalues/", views.AttributeValueListAPIView.as_view()),
    # Attribute Objects
    path("attributes/", views.AttributeAPIViewSet.as_view({"get": "list"})),
    path("attribute/", views.AttributeCreateAPIView.as_view()),
    path(
        "attribute/<int:pk>/",
        views.AttributeAPIViewSet.as_view(
            {
                "get": "retrieve",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
    ),
    # Brand Objects
    path("brand/", views.BrandCreateAPIView.as_view()),
    path("brand/<int:pk>/", views.BrandGetUpdateDestroyAPIView.as_view()),
    path("brands/", views.BrandListAPIView.as_view()),
    # Product Objects
    path("product/", views.ProductCreateAPIView.as_view()),
    path("product/<int:pk>/", views.ProductGetUpdateDestroyAPIView.as_view()),
    path("products/", views.ProductListAPIView.as_view()),
    # Nomenclature Objects
    path("nomenclature/", views.NomenclatureCreateAPIView.as_view()),
    path("nomenclature/<int:pk>/", views.NomenclatureGetUpdateDestroyAPIView.as_view()),
    path("nomenclatures/", views.NomenclatureListAPIView.as_view()),
    # Image Objects
    path("image/", views.ImageCreateAPIView.as_view()),
    path("image/<int:pk>/", views.ImageGetUpdateDestroyAPIView.as_view()),
    path("images/", views.ImageListAPIView.as_view()),
    # ShippingAddress Objects
    path("shipping_address/", views.ShippingAddressCreateAPIView.as_view()),
    path(
        "shipping_address/<int:pk>/",
        views.ShippingAddressGetUpdateDestroyAPIView.as_view(),
    ),
    path("shipping_addresses/", views.ShippingAddressListAPIView.as_view()),
    # Order Objects
    path("order/", views.OrderCreateAPIView.as_view()),
    path("order/<int:pk>/", views.OrderGetUpdateDestroyAPIView.as_view()),
    path("orders/", views.OrderListAPIView.as_view()),
    # OrderItem Objects
    path("orderitem/", views.OrderItemCreateAPIView.as_view()),
    path("orderitem/<int:pk>/", views.OrderItemGetUpdateDestroyAPIView.as_view()),
    path("orderitems/", views.OrderItemListAPIView.as_view()),
    # Invoice Objects
    path("invoice/<int:pk>/", views.InvoiceDetailAPIView.as_view()),
    # Import
    path("import/", views.ImportAPIView.as_view()),
]

eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # Project paths
    path("admin/", admin.site.urls),
    path("api/v1/", include("api.urls")),
    path("", include("products.urls")),
    path("orders/", include("orders.urls")),
    path("users/", include("users.urls")),
    path("cart/", include("cart.urls")),
    # Swagger
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # import mimetypes

    # mimetypes.add_type("application/javascript", ".js", True)
    urlpatterns = [path("__debug__/", include("debug_toolbar.urls"))] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop/orders/urls.py
from django.urls import path

from . import views


app_name = "orders"
urlpatterns = [
    path("", views.OrderListView.as_view(), name="order_list"),
    # Shipping Address
    path(
        "create_shipping_address",
        views.CreateShippingAddressView.as_view(),
        name="create_shipping_address",
    ),
    path(
        "shipping_address",
        views.ShippingAddressListView.as_view(),
        name="shipping_address_list",
    ),
    path(
        "shipping_address_inactive",
        views.ShippingAddressInactiveListView.as_view(),
        name="shipping_address_inactive_list",
    ),
    path(
        "update/shipping_address/<int:pk>/",
        views.ShippingAddressUpdateView.as_view(),
        name="update_shipping_address",
    ),
    path("order/<slug:slug>/", views.OrderDetailView.as_view(), name="order_detail"),
]

eshop/products/urls.py
from django.urls import path

from . import views


app_name = "products"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    # Brands
    path("brands/", views.BrandListView.as_view(), name="brand_list"),
    path("brand/<slug:slug>/", views.BrandDetailView.as_view(), name="brand_detail"),
    # ProductVariant
    path(
        "products/<slug:product_variant_slug>",
        views.ProductVariantDetailView.as_view(),
        name="product_variant",
    ),
    path(
        "product-variants/",
        views.ProductVariantListView.as_view(),
        name="product_variant_list",
    ),
    path(
        "category/<slug:slug>/<slug:product_slug>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
]

eshop/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views


app_name = "users"

urlpatterns = [
    # Login, registration, logout, password reset
    path("registration/", views.RegisterUser.as_view(), name="registration"),
    path(
        "registration_confirmation/",
        views.registration_confirmation,
        name="registration_confirmation",
    ),
    path("login/", views.LoginUser.as_view(), name="login"),
    path("logout/", views.LogOutUser.as_view(), name="logout"),
    path("reset_password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset_password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset_password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset_password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    # User detail, update
    path("profile/<str:username>/", views.ProfileDetailView.as_view(), name="profile"),
    path(
        "update/<int:pk>/",
        views.ProfileUpdateView.as_view(),
        name="update_profile",
    ),
]

eshop/orders/models.py
import io

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django_extensions.db.fields import AutoSlugField
from django.core.files.base import ContentFile
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

from .utils import generate_order_number, generate_invoice_number
from .mixins import TimeStampedModel
from products.utils import my_slugify_function
from products.models import Nomenclature


class ShippingAddress(models.Model):
    user = models.ForeignKey(
        User, related_name="shipping_addresses", on_delete=models.CASCADE
    )
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=20)
    is_default = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.user.username} - {self.address}, {self.city}, {self.country}"

    class Meta:
        verbose_name = "Shipping Address"
        verbose_name_plural = "Shipping Addresses"


class PaymentMethod(models.Model):
    PAYMENT_METHOD_CHOICE = {
        "AP": "Advanced Payment",
        "PP": "Post Payment",
        "CC": "Credit Card",
    }
    name = models.CharField(max_length=2, choices=PAYMENT_METHOD_CHOICE, unique=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "Payment Method"
        verbose_name_plural = "Payment Methods"


class Order(TimeStampedModel):
    STATUS_CHOICE = {
        "pending": "Pending",
        "completed": "Completed",
        "shipped": "Shipped",
        "delivered": "Delivered",
        "cancelled": "Cancelled",
    }

    user = models.ForeignKey(User, related_name="orders", on_delete=models.CASCADE)
    shipping_address = models.ForeignKey(
        ShippingAddress, related_name="orders", on_delete=models.CASCADE
    )
    code = models.CharField(max_length=10, default=generate_order_number, unique=True)
    status = models.CharField(max_length=9, choices=STATUS_CHOICE, default="pending")
    slug = AutoSlugField(populate_from="code", slugify_function=my_slugify_function)
    payment_method = models.ForeignKey(
        PaymentMethod,
        on_delete=models.CASCADE,
        related_name="orders",
        default=1,
    )

    def __str__(self):
        return self.code

    def get_absolute_url(self):
        return reverse("orders:order_detail", kwargs={"slug": self.slug})

    def total_price(self):
        return sum([item.total_price() for item in self.items.all()])

    def total_pieces(self):
        return sum([item.quantity for item in self.items.all()])

    class Meta:
        verbose_name = "Order"
        verbose_name_plural = "Orders"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items")
    nomenclature = models.ForeignKey(
        Nomenclature, on_delete=models.CASCADE, related_name="items"
    )
    quantity = models.PositiveIntegerField()

    def total_price(self):
        return self.quantity * self.nomenclature.price

    def __str__(self):
        return f"Order Item of the order {self.order}: Nomenclature {self.nomenclature.code} - ({self.quantity} units)"

    class Meta:
        verbose_name = "Order Item"
        verbose_name_plural = "Order Items"


class Invoice(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="invoices")
    number = models.CharField(
        max_length=10, default=generate_invoice_number, unique=True
    )
    file = models.FileField(upload_to="invoices/", blank=True, null=True)

    def __str__(self):
        return self.number

    def generate_invoice_file(self):
        buffer = io.BytesIO()

        p = canvas.Canvas(buffer, pagesize=A4)
        p.drawString(100, 750, f"Invoice Number: {self.number}")
        p.drawString(100, 730, f"Order Code: {self.order.code}")
        p.drawString(
            100, 710, f"Order Date: {self.order.created_at.strftime('%Y-%m-%d')}"
        )

        p.showPage()
        p.save()

        pdf = buffer.getvalue()
        buffer.close()

        return ContentFile(pdf, f"invoice_{self.number}.pdf")

    def save(self, *args, **kwargs):
        if not self.file:
            self.file = self.generate_invoice_file()
        super().save(*args, **kwargs)

eshop/orders/forms.py
from typing import Any, Mapping
from django.core.files.base import File
from django.db.models.base import Model
from django.forms import ModelForm, CharField, BooleanField
from django.forms.utils import ErrorList

from .models import ShippingAddress


class CreateShippingAddressForm(ModelForm):

    class Meta:
        model = ShippingAddress
        exclude = ["user", "is_default", "is_active"]

    address = CharField(max_length=100, required=True)
    city = CharField(max_length=100, required=True)
    country = CharField(max_length=100, required=True)
    postal_code = CharField(max_length=20, required=True)


class UpdateShippingAddressForm(ModelForm):

    class Meta:
        model = ShippingAddress
        exclude = ["user", "is_default"]

    address = CharField(max_length=100, required=True)
    city = CharField(max_length=100, required=True)
    country = CharField(max_length=100, required=True)
    postal_code = CharField(max_length=20, required=True)
    is_active = BooleanField(required=True)

eshop/orders/views.py
from typing import Any

from django.db.models.query import QuerySet
from django.db.models import Prefetch
from django.urls import reverse
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
)
from django.http import HttpRequest
from django.contrib.auth.models import User

from .models import Order, ShippingAddress, OrderItem
from .forms import CreateShippingAddressForm, UpdateShippingAddressForm


# Order
class OrderDetailView(DetailView):
    model = Order
    template_name = "orders/order_detail.html"
    context_object_name = "order"

    def get_queryset(self) -> QuerySet[Any]:
        order = Order.objects.select_related(
            "user",
            "shipping_address",
        ).prefetch_related(
            Prefetch(
                "items",
                queryset=OrderItem.objects.select_related(
                    "nomenclature",
                ),
            ),
        )
        return order


class OrderListView(ListView):
    model = Order
    template_name = "orders/order_list.html"
    context_object_name = "orders"

    def get_queryset(self) -> QuerySet[Order]:
        if not self.request.user.is_authenticated:
            return reverse("products:index")
        return (
            Order.objects.filter(user=self.request.user)
            .select_related("user", "shipping_address")
            .prefetch_related("items__nomenclature")
            .order_by("-created_at")
        )


# Shipping Address
class CreateShippingAddressView(CreateView):
    model = ShippingAddress
    form_class = CreateShippingAddressForm
    template_name = "orders/create_shipping_address.html"
    request = HttpRequest()

    def form_valid(self, form):
        user = User.objects.get(id=self.request.user.id)
        form.instance.user = user
        self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse("users:profile", kwargs={"username": self.object.user.username})


class ShippingAddressListView(ListView):
    model = ShippingAddress
    template_name = "orders/shipping_address_list.html"
    context_object_name = "addresses"

    def get_queryset(self) -> QuerySet[ShippingAddress]:
        return (
            ShippingAddress.objects.filter(user=self.request.user)
            .filter(is_active=True)
            .select_related("user")
            .order_by("city")
        )


class ShippingAddressInactiveListView(ListView):
    model = ShippingAddress
    template_name = "orders/shipping_address_inactive_list.html"
    context_object_name = "addresses"

    def get_queryset(self) -> QuerySet[ShippingAddress]:
        return (
            ShippingAddress.objects.filter(user=self.request.user)
            .filter(is_active=False)
            .select_related("user")
            .order_by("city")
        )


class ShippingAddressUpdateView(UpdateView):
    model = ShippingAddress
    context_object_name = "shipping_address"
    form_class = UpdateShippingAddressForm
    template_name_suffix = "_update_form"

    def get_success_url(self) -> str:
        return reverse("orders:shipping_address_list")

eshop/orders/templates/orders/create_shipping_address.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}
<div class="address">
    <div class="container">
        <div class="address__row">
            <form class="address__form" method="post">
                {% csrf_token %}
                <div class="address__field">
                    <label for="id_address">{{ form.address.label }}:</label>
                    {{ form.address }}
                </div>
                <div class="address__field">
                    <label for="id_address">{{ form.city.label }}:</label>
                    {{ form.city }}
                </div>
                <div class="address__field">
                    <label for="id_address">{{ form.country.label }}:</label>
                    {{ form.country }}
                </div>
                <div class="address__field">
                    <label for="id_address">{{ form.postal_code.label }}:</label>
                    {{ form.postal_code }}
                </div>
                <div class="address__submit__input">
                    <input type="submit" value="Create">
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

eshop/orders/templates/orders/order_detail.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}

<div class="order">
    <div class="container">
        <div class="order__row">
        {% if not request.user.is_authenticated %}
        <script>
            window.location.href = "{% url 'products:index' %}";
        </script>
        {% else %}
            <div class="back__url">
                <a href="{% url 'users:profile' username=request.user.username %}">Back</a>
            </div>
            <div class="order__info">
                <div class="order__title">
                    <h2>Order Summary - {{ order.code }}</h2>
                </div>
                <div class="order__goods">
                    {% for orderitem in order.items.all %}
                    <div class="order__orderitem">
                        <div class="orderitem__detail">
                            {{ orderitem.nomenclature.product_variant.product.name }}
                        </div>
                        <div class="orderitem__detail">
                            {{ orderitem.nomenclature.product_variant.attributes.attribute_value.value }}
                        </div>
                        <div class="orderitem__detail">
                            {{ orderitem.nomenclature.attributes.attribute_value.value }}
                        </div>
                        <div class="orderitem__detail">
                            {{ orderitem.nomenclature.code }}
                        </div>
                        <div class="orderitem__detail">
                            {{ orderitem.quantity }}
                        </div>
                        <div class="orderitem__detail">
                            {{ orderitem.nomenclature.price }}
                        </div>
                        <div class="orderitem__detail">
                            {{ orderitem.total_price }}
                        </div>
                    </div>
                    {% endfor %}
                    <div class="order__info">
                        <div class="total__price">
                            Total: {{ order.total_price }} EUR
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

eshop/orders/templates/orders/order_list.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}

<div class="orders">
    <div class="container">
        <div class="orders__row">
        {% if not request.user.is_authenticated %}
        <script>
            window.location.href = "{% url 'products:index' %}";
        </script>
        {% else %}
            <div class="orders__backurl">
                <a href="{% url 'users:profile' username=request.user.username %}">My profile</a>
            </div>
            {% if orders %}
            <ul class="orders__list">
                {% for order in orders %}
                <li>
                    <div class="orders__url"><a href="{{ order.get_absolute_url }}"> Order: {{ order.code }}</a></div>
                    <div class="orders__cost">Total cost: {{ order.total_price }} EUR</div>
                    <div class="orders__pieces">Ordered pieces: {{ order.total_pieces }}</div>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <div class="orders__none detail-none">
                <p>You haven`t purchased yet.</p>
            </div>
            {% endif %}
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

eshop/orders/templates/orders/shipping_address_inactive_list.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}

<br>
<a href="{% url 'users:profile' username=request.user.username %}">BACK</a>
<br>
<br>
Shipping Addresses (Inactive):
<br>
<br>

{% for address in addresses %}

    Street: {{ address.address }}<br/>
    City: {{ address.city }}<br/>
    Country: {{ address.country }}<br/>
    Postal Code: {{ address.postal_code }}<br/>
    Active: {{ address.is_active }}<br/>
    Default: {{ address.is_default }}<br/>
    <a href="{% url 'orders:update_shipping_address' pk=address.id %}">Update SA</a><br/>
    <br/>
    <br/>

{% endfor %}

{% endblock %}

eshop/orders/templates/orders/shipping_address_list.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}

<div class="addresses">
    <div class="container">
        <div class="address__list__row">
            <h2>Active Shipping Addresses</h2>
            {% if addresses %}
            <div class="addresses__info">
                {% for address in addresses %}
                <div class="addresses__details">
                    <div class="addresses__detail">
                        <div>
                            {{ address.address }}
                        </div>
                        <div>
                            {{ address.city }}
                        </div>
                        <div>
                            {{ address.country }}
                        </div>
                        <div>
                            {{ address.postal_code }}
                        </div>
                    </div>
                    <div class="addresses__update__url">
                        <a href="{% url 'orders:update_shipping_address' pk=address.id %}">Update</a>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <div class="detail-none">
                <p>You haven`t add any shipping address</p>
            </div>
            {% endif %}
        </div>
    </div>
</div>

<!-- <a href="{% url 'users:profile' username=request.user.username %}">BACK</a> -->
{% endblock %}

eshop/orders/templates/orders/shippingaddress_update_form.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}
<div class="address">
    <div class="container">
        <div class="address__row">
            <form class="address__form" method="post" action="{% url 'orders:update_shipping_address' pk=shipping_address.id %}">
                {% csrf_token %}
                <div class="address__field">
                    <label for="id_address">{{ form.address.label }}:</label>
                    {{ form.address }}
                </div>
                <div class="address__field">
                    <label for="id_address">{{ form.city.label }}:</label>
                    {{ form.city }}
                </div>
                <div class="address__field">
                    <label for="id_address">{{ form.country.label }}:</label>
                    {{ form.country }}
                </div>
                <div class="address__field">
                    <label for="id_address">{{ form.postal_code.label }}:</label>
                    {{ form.postal_code }}
                </div>
                <div class="address__field">
                    <label for="id_address">{{ form.is_active.label }}:</label>
                    {{ form.is_active }}
                </div>
                <div class="address__submit__input">
                    <input type="submit" value="Update">
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}