eshop/api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views


app_name = "api"
urlpatterns = [
    # Token
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    # AttributeName Objects
    path("attributename/", views.AttributeNameCreateAPIView.as_view()),
    path(
        "attributename/<int:pk>/", views.AttributeNameGetUpdateDestroyAPIView.as_view()
    ),
    path("attributenames/", views.AttributeNameListAPIView.as_view()),
    # AttributeValue Objects
    path("attributevalue/", views.AttributeValueCreateAPIView.as_view()),
    path(
        "attributevalue/<int:pk>/",
        views.AttributeValueGetUpdateDestroyAPIView.as_view(),
    ),
    path("attributevalues/", views.AttributeValueListAPIView.as_view()),
    # Attribute Objects
    path("attributes/", views.AttributeAPIViewSet.as_view({"get": "list"})),
    path("attribute/", views.AttributeCreateAPIView.as_view()),
    path(
        "attribute/<int:pk>/",
        views.AttributeAPIViewSet.as_view(
            {
                "get": "retrieve",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
    ),
    # Brand Objects
    path("brand/", views.BrandCreateAPIView.as_view()),
    path("brand/<int:pk>/", views.BrandGetUpdateDestroyAPIView.as_view()),
    path("brands/", views.BrandListAPIView.as_view()),
    # Product Objects
    path("product/", views.ProductCreateAPIView.as_view()),
    path("product/<int:pk>/", views.ProductGetUpdateDestroyAPIView.as_view()),
    path("products/", views.ProductListAPIView.as_view()),
    # Nomenclature Objects
    path("nomenclature/", views.NomenclatureCreateAPIView.as_view()),
    path("nomenclature/<int:pk>/", views.NomenclatureGetUpdateDestroyAPIView.as_view()),
    path("nomenclatures/", views.NomenclatureListAPIView.as_view()),
    # Image Objects
    path("image/", views.ImageCreateAPIView.as_view()),
    path("image/<int:pk>/", views.ImageGetUpdateDestroyAPIView.as_view()),
    path("images/", views.ImageListAPIView.as_view()),
    # ShippingAddress Objects
    path("shipping_address/", views.ShippingAddressCreateAPIView.as_view()),
    path(
        "shipping_address/<int:pk>/",
        views.ShippingAddressGetUpdateDestroyAPIView.as_view(),
    ),
    path("shipping_addresses/", views.ShippingAddressListAPIView.as_view()),
    # Order Objects
    path("order/", views.OrderCreateAPIView.as_view()),
    path("order/<int:pk>/", views.OrderGetUpdateDestroyAPIView.as_view()),
    path("orders/", views.OrderListAPIView.as_view()),
    # OrderItem Objects
    path("orderitem/", views.OrderItemCreateAPIView.as_view()),
    path("orderitem/<int:pk>/", views.OrderItemGetUpdateDestroyAPIView.as_view()),
    path("orderitems/", views.OrderItemListAPIView.as_view()),
    # Invoice Objects
    path("invoice/<int:pk>/", views.InvoiceDetailAPIView.as_view()),
    # Import
    path("import/", views.ImportAPIView.as_view()),
]

eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # Project paths
    path("admin/", admin.site.urls),
    path("api/v1/", include("api.urls")),
    path("", include("products.urls")),
    path("orders/", include("orders.urls")),
    path("users/", include("users.urls")),
    path("cart/", include("cart.urls")),
    # Swagger
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # import mimetypes

    # mimetypes.add_type("application/javascript", ".js", True)
    urlpatterns = [path("__debug__/", include("debug_toolbar.urls"))] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop/orders/urls.py
from django.urls import path

from . import views


app_name = "orders"
urlpatterns = [
    path("", views.OrderListView.as_view(), name="order_list"),
    # Shipping Address
    path(
        "create_shipping_address",
        views.CreateShippingAddressView.as_view(),
        name="create_shipping_address",
    ),
    path(
        "shipping_address",
        views.ShippingAddressListView.as_view(),
        name="shipping_address_list",
    ),
    path(
        "shipping_address_inactive",
        views.ShippingAddressInactiveListView.as_view(),
        name="shipping_address_inactive_list",
    ),
    path(
        "update/shipping_address/<int:pk>/",
        views.ShippingAddressUpdateView.as_view(),
        name="update_shipping_address",
    ),
    path("order/<slug:slug>/", views.OrderDetailView.as_view(), name="order_detail"),
]

eshop/products/urls.py
from django.urls import path

from . import views


app_name = "products"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    # Brands
    path("brands/", views.BrandListView.as_view(), name="brand_list"),
    path("brand/<slug:slug>/", views.BrandDetailView.as_view(), name="brand_detail"),
    # ProductVariant
    path(
        "products/<slug:product_variant_slug>",
        views.ProductVariantDetailView.as_view(),
        name="product_variant",
    ),
    path(
        "product-variants/",
        views.ProductVariantListView.as_view(),
        name="product_variant_list",
    ),
    path(
        "category/<slug:slug>/<slug:product_slug>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
]

eshop/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views


app_name = "users"

urlpatterns = [
    # Login, registration, logout, password reset
    path("registration/", views.RegisterUser.as_view(), name="registration"),
    path(
        "registration_confirmation/",
        views.registration_confirmation,
        name="registration_confirmation",
    ),
    path("login/", views.LoginUser.as_view(), name="login"),
    path("logout/", views.LogOutUser.as_view(), name="logout"),
    path("reset_password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset_password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset_password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset_password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    # User detail, update
    path("profile/<str:username>/", views.ProfileDetailView.as_view(), name="profile"),
    path(
        "update/<int:pk>/",
        views.ProfileUpdateView.as_view(),
        name="update_profile",
    ),
]

eshop/company/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.validators import EmailValidator

from .mixins import MixinsModel


class Company(MixinsModel):
    address = models.CharField(max_length=100, null=False)
    city = models.CharField(max_length=30, unique=True, null=False)
    postal_code = models.PositiveIntegerField(
        validators=[MinValueValidator(10000), MaxValueValidator(99999)]
    )
    country = models.CharField(max_length=30, null=False)
    phone = models.PositiveIntegerField(
        validators=[MinValueValidator(100000000), MaxValueValidator(999999999)]
    )
    email = models.EmailField(validators=[EmailValidator()], unique=True)
    is_legal_address = models.BooleanField()

    class Meta:
        verbose_name = "Company"
        verbose_name_plural = "Companies"


class Bank(MixinsModel):
    swift = models.CharField(max_length=6, unique=True, null=False)

    class Meta:
        verbose_name = "Bank"
        verbose_name_plural = "Banks"


class BankAccount(models.Model):
    account_number = models.CharField(max_length=20, unique=True, null=False)

    class Meta:
        verbose_name = "Bank Account"
        verbose_name_plural = "Bank Accounts"

    def __str__(self) -> str:
        return self.account_number


class CompanyBankAccount(models.Model):
    bank = models.ForeignKey(Bank, on_delete=models.CASCADE, related_name="accounts")
    company = models.ForeignKey(
        Company, on_delete=models.CASCADE, related_name="accounts"
    )
    bank_account = models.ForeignKey(
        BankAccount, on_delete=models.CASCADE, related_name="accounts"
    )

    class Meta:
        verbose_name = "Company Bank Account"
        verbose_name_plural = "Company Bank Accounts"

eshop/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django_extensions.db.fields import AutoSlugField

from products.utils import my_slugify_function


# Create your models here.

eshop/users/forms.py
from typing import Any
from django.forms import (
    ModelForm,
    CharField,
    EmailField,
    EmailInput,
    TextInput,
    PasswordInput,
    ModelChoiceField,
    ValidationError,
)

from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterUserForm(UserCreationForm):
    first_name = CharField(label="First Name", widget=TextInput())
    last_name = CharField(label="Last Name", widget=TextInput())
    username = CharField(label="Login", widget=TextInput())
    email = EmailField(label="Email", widget=EmailInput())
    password1 = CharField(label="Password", widget=PasswordInput())
    password2 = CharField(
        label="Password confirmation",
        widget=PasswordInput(),
    )

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )


class LoginUserForm(AuthenticationForm):
    username = CharField(label="Login", widget=TextInput())
    password = CharField(label="Password", widget=PasswordInput())


class UserUpdateFrom(ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "email"]

    first_name = CharField(max_length=50, required=True)
    last_name = CharField(max_length=50, required=True)

eshop/users/views.py
from typing import Any

from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    FormView,
    UpdateView,
    DeleteView,
)
from django.contrib.auth.views import (
    LoginView,
    PasswordResetView,
    LogoutView,
    PasswordResetConfirmView,
)
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin

from .forms import RegisterUserForm, LoginUserForm, UserUpdateFrom
from orders.models import Order


# Create your views here.
# User
def registration_confirmation(request):
    return render(request, "users/registration_confirmation.html")


# Registration
class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = "users/registration.html"

    def form_valid(self, form):
        user = form.save()
        user.save()
        return redirect("users:registration_confirmation")


# Log in
class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = "users/login.html"


# Log out
class LogOutUser(LogoutView):
    # Logging out via GET requests to the built-in logout view is deprecated. Use POST requests instead.
    next_page = "/"


# Password reset
class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = "users/password_reset.html"
    email_template_name = "users/password_reset_email.html"
    html_email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")
    success_message = (
        "An email with instructions to reset your password has been sent to %(email)s."
    )
    subject_template_name = "users/password_reset_subject.txt"


class ProfileDetailView(DetailView):
    template_name = "users/user_detail.html"

    def get(self, request, username):
        # получаем пользователя по username если он существует
        user = get_object_or_404(User, username=username)
        # передаем его в шаблон как profile
        orders = (
            Order.objects.filter(user=user)
            .select_related("user", "shipping_address")
            .prefetch_related("items__nomenclature")
            .order_by("created_at")
        )
        turnover = sum([order.total_price() for order in orders])
        return render(
            request, self.template_name, {"profile": user, "turnover": turnover}
        )


class ProfileUpdateView(UpdateView):
    model = User
    form_class = UserUpdateFrom
    context_object_name = "user"
    template_name = "users/user_update_form.html"

    def get_success_url(self):
        return reverse("users:profile", kwargs={"username": self.object.username})

eshop/users/templates/users/login.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}
<div class="form-container">
    <form method="post" class="styled-form">
        {% csrf_token %}
        <div class="form-group">
            {{ form.username.label_tag }}{{ form.username }}
        </div>
        <div class="form-group">
            {{ form.password.label_tag }}{{ form.password }}
        </div>
        <input type="submit" value="Submit" class="submit-btn">
    </form>
    <hr class="divider">
    <a href="{% url 'users:password_reset' %}" class="forgot-password-link">Forgot Password?</a>
</div>
{% endblock %}

eshop/users/templates/users/password_reset.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Request password reset</button>
    </form>
{% endblock %}

eshop/users/templates/users/password_reset_complete.html
{% extends 'products/base.html' %}
{% load static %}


{% block content %}
    <h3>Password reset complete!</h3>
    <p>You can log in now.</p>
{% endblock %}

eshop/users/templates/users/password_reset_confirm.html
{% extends 'products/base.html' %}
{% load static %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save new password</button>
    </form>
{% endblock %}

eshop/users/templates/users/password_reset_done.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}
    <h2>Password reset request sent</h2>
    <p>We've emailed you with instructions on how to reset your password.</p>
{% endblock %}

eshop/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
    <div>
        <p>Hi {{ user.first_name }},</p>
        <p>You requested a password reset for your account. Please follow this link to set a new password:</p>
        <p>
            <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
                E-Comm - Password Reset
            </a>
        </p>
        <p>If you didn't request a password reset, please ignore this email.</p>
        <p>Thanks,</p>
        <p>The Our Team</p>
    </div>
</body>
{% endautoescape %}

eshop/users/templates/users/registration.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}
<div class="form-container">
    <form method="post" class="styled-form">
        {% csrf_token %}
        <div class="form-group">
            {{ form.first_name.label_tag }}{{ form.first_name }}
        </div>
        <div class="form-group">
            {{ form.last_name.label_tag }}{{ form.last_name }}
        </div>
        <div class="form-group">
            {{ form.username.label_tag }}{{ form.username }}
        </div>
        <div class="form-group">
            {{ form.email.label_tag }}{{ form.email }}
        </div>
        <div class="form-group">
            {{ form.password1.label_tag }}{{ form.password1 }}
        </div>
        <div class="form-group">
            {{ form.password2.label_tag }}{{ form.password2 }}
        </div>
        <input type="submit" value="Submit" class="submit-btn">
    </form>
</div>
{% endblock %}

eshop/users/templates/users/registration_confirmation.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}
<div class="confirmation-container">
    <h2>Thank you for the registration!</h2>
    <p>You can now log in</p>
</div>
{% endblock %}

eshop/users/templates/users/user_detail.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}

<div class="profile">
    <div class="container">
        <div class="profile__row">
        {% if request.user.is_authenticated and request.user.id == user.id %}
            <div class="profile__menu">
                <div class="profile__url">
                    <a href="{% url 'users:update_profile' pk=user.id %}">Edit profile</a>
                </div>
                <div class="profile__url">
                    <a href="{% url 'orders:order_list' %}">Orders</a>
                </div>    
                <div class="profile__url">
                    <a href="{% url 'orders:shipping_address_list' %}">Shipping addresses</a>
                </div>
                <div class="profile__url">
                    <a href="{% url 'orders:create_shipping_address' %}">Add shipping address</a>
                </div>
            </div>
            <div class="profile__info">
                <div class="profile__card">
                    <div class="profile__title">User details</div>
                    <div class="profile_overview">
                        <div class="profile__data">
                            <div class="profile__keys">
                                <div class="profile__key">First Name:</div>
                                <div class="profile__key">Last Name:</div>
                                <div class="profile__key">E-mail:</div>
                                <div class="profile__key">Last login:</div>
                                <div class="profile__key">Date joined:</div>
                            </div>
                            <div class="profile__values">
                                <div class="profile__value">{{ user.first_name }}</div>
                                <div class="profile__value">{{ user.last_name }}</div>
                                <div class="profile__value">{{ user.email }}</div>
                                <div class="profile__value">{{ user.last_login }}</div>
                                <div class="profile__value">{{ user.date_joined }}</div>
                            </div>
                        </div>
                        <div class="profile_stats">
                            <div class="profile__orders">
                                <h2>Total orders</h2>
                                <div>{{ user.orders.all|length }}</div>
                            </div>
                            <div class="profile__turnover">
                                <h2>Turnover</h2>
                                <div>{{ turnover }} EUR</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <script>
            window.location.href = "{% url 'products:index' %}";
        </script>
        {% endif %}
    </div>
</div>
{% endblock %}

eshop/users/templates/users/user_update_form.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}

<div class="profile__update">
    <div class="container">
        <div class="profile__update__row">
            <form class="profile__update__form" method="post" action="{% url 'users:update_profile' pk=user.id %}">
                {% csrf_token %}
                <div class="profile__form__row">
                    <label for="id_first_name">First Name:</label>
                    {{ form.first_name }}
                </div>
                <div class="profile__form__row">
                    <label for="id_last_name">Last Name:</label>
                    {{ form.last_name }}
                </div>
                <div class="profile__form__row">
                    <label for="id_username">Username:</label>
                    {{ form.username }}
                </div>
                <div class="profile__form__row">
                    <label for="id_email">Email:</label>
                    {{ form.email }}
                </div>
                <div class="profile__form__submit__input">
                    <input type="submit" value="Update">
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}