eshop/api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views


app_name = "api"
urlpatterns = [
    # Token
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    # AttributeName Objects
    path("attributename/", views.AttributeNameCreateAPIView.as_view()),
    path(
        "attributename/<int:pk>/", views.AttributeNameGetUpdateDestroyAPIView.as_view()
    ),
    path("attributenames/", views.AttributeNameListAPIView.as_view()),
    # AttributeValue Objects
    path("attributevalue/", views.AttributeValueCreateAPIView.as_view()),
    path(
        "attributevalue/<int:pk>/",
        views.AttributeValueGetUpdateDestroyAPIView.as_view(),
    ),
    path("attributevalues/", views.AttributeValueListAPIView.as_view()),
    # Attribute Objects
    path("attributes/", views.AttributeAPIViewSet.as_view({"get": "list"})),
    path("attribute/", views.AttributeCreateAPIView.as_view()),
    path(
        "attribute/<int:pk>/",
        views.AttributeAPIViewSet.as_view(
            {
                "get": "retrieve",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
    ),
    # Brand Objects
    path("brand/", views.BrandCreateAPIView.as_view()),
    path("brand/<int:pk>/", views.BrandGetUpdateDestroyAPIView.as_view()),
    path("brands/", views.BrandListAPIView.as_view()),
    # Product Objects
    path("product/", views.ProductCreateAPIView.as_view()),
    path("product/<int:pk>/", views.ProductGetUpdateDestroyAPIView.as_view()),
    path("products/", views.ProductListAPIView.as_view()),
    # Nomenclature Objects
    path("nomenclature/", views.NomenclatureCreateAPIView.as_view()),
    path("nomenclature/<int:pk>/", views.NomenclatureGetUpdateDestroyAPIView.as_view()),
    path("nomenclatures/", views.NomenclatureListAPIView.as_view()),
    # Image Objects
    path("image/", views.ImageCreateAPIView.as_view()),
    path("image/<int:pk>/", views.ImageGetUpdateDestroyAPIView.as_view()),
    path("images/", views.ImageListAPIView.as_view()),
    # ShippingAddress Objects
    path("shipping_address/", views.ShippingAddressCreateAPIView.as_view()),
    path(
        "shipping_address/<int:pk>/",
        views.ShippingAddressGetUpdateDestroyAPIView.as_view(),
    ),
    path("shipping_addresses/", views.ShippingAddressListAPIView.as_view()),
    # Order Objects
    path("order/", views.OrderCreateAPIView.as_view()),
    path("order/<int:pk>/", views.OrderGetUpdateDestroyAPIView.as_view()),
    path("orders/", views.OrderListAPIView.as_view()),
    # OrderItem Objects
    path("orderitem/", views.OrderItemCreateAPIView.as_view()),
    path("orderitem/<int:pk>/", views.OrderItemGetUpdateDestroyAPIView.as_view()),
    path("orderitems/", views.OrderItemListAPIView.as_view()),
    # Invoice Objects
    path("invoice/<int:pk>/", views.InvoiceDetailAPIView.as_view()),
    # Import
    path("import/", views.ImportAPIView.as_view()),
]

eshop/cart/urls.py
from django.urls import path
from .views import (
    CartDetailView,
    CheckoutView,
    OrderConfirmationView,
)

app_name = "cart"
urlpatterns = [
    path("my-cart/", CartDetailView.as_view(), name="cart_detail"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path(
        "order-confirmation/",
        OrderConfirmationView.as_view(),
        name="order_confirmation",
    ),
]

eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # Project paths
    path("admin/", admin.site.urls),
    path("api/v1/", include("api.urls")),
    path("", include("products.urls")),
    path("orders/", include("orders.urls")),
    path("users/", include("users.urls")),
    path("cart/", include("cart.urls")),
    # Swagger
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # import mimetypes

    # mimetypes.add_type("application/javascript", ".js", True)
    urlpatterns = [path("__debug__/", include("debug_toolbar.urls"))] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop/orders/urls.py
from django.urls import path

from . import views


app_name = "orders"
urlpatterns = [
    path("", views.OrderListView.as_view(), name="order_list"),
    # Shipping Address
    path(
        "create_shipping_address",
        views.CreateShippingAddressView.as_view(),
        name="create_shipping_address",
    ),
    path(
        "shipping_address",
        views.ShippingAddressListView.as_view(),
        name="shipping_address_list",
    ),
    path(
        "shipping_address_inactive",
        views.ShippingAddressInactiveListView.as_view(),
        name="shipping_address_inactive_list",
    ),
    path(
        "update/shipping_address/<int:pk>/",
        views.ShippingAddressUpdateView.as_view(),
        name="update_shipping_address",
    ),
    path("order/<slug:slug>/", views.OrderDetailView.as_view(), name="order_detail"),
]

eshop/products/urls.py
from django.urls import path

from . import views


app_name = "products"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    # Brands
    path("brands/", views.BrandListView.as_view(), name="brand_list"),
    path("brand/<slug:slug>/", views.BrandDetailView.as_view(), name="brand_detail"),
    # ProductVariant
    path(
        "products/<slug:product_variant_slug>",
        views.ProductVariantDetailView.as_view(),
        name="product_variant",
    ),
    path(
        "product-variants/",
        views.ProductVariantListView.as_view(),
        name="product_variant_list",
    ),
    path(
        "category/<slug:slug>/<slug:product_slug>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
]

eshop/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views


app_name = "users"

urlpatterns = [
    # Login, registration, logout, password reset
    path("registration/", views.RegisterUser.as_view(), name="registration"),
    path(
        "registration_confirmation/",
        views.registration_confirmation,
        name="registration_confirmation",
    ),
    path("login/", views.LoginUser.as_view(), name="login"),
    path("logout/", views.LogOutUser.as_view(), name="logout"),
    path("reset_password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset_password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset_password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset_password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    # User detail, update
    path("profile/<str:username>/", views.ProfileDetailView.as_view(), name="profile"),
    path(
        "update/<int:pk>/",
        views.ProfileUpdateView.as_view(),
        name="update_profile",
    ),
]

eshop/products/views.py
from django.core.cache import cache
from django.db.models import Prefetch
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import (
    ListView,
    DetailView,
)

from .models import (
    Brand,
    Product,
    Attribute,
    ProductVariant,
    Nomenclature,
    Category,
    Subcategory,
)

from cart.models import Cart, CartItem


class IndexView(View):
    def get(self, request):
        return render(request, "products/index.html")


# Brand
class BrandDetailView(DetailView):
    model = Brand
    template_name = "products/brand_detail.html"
    context_object_name = "brand"


class BrandListView(ListView):
    model = Brand
    template_name = "products/brand_list.html"
    context_object_name = "brands"

    def get_queryset(self) -> QuerySet[Brand]:
        return Brand.objects.order_by("name")


# Product
class ProductDetailView(DetailView):
    model = Product
    slug_url_kwarg = "product_slug"
    template_name = "products/product_detail.html"
    context_object_name = "product"

    def get_queryset(self):
        product = Product.objects.select_related(
            "brand", "category", "subcategory"
        ).prefetch_related(
            "attributes__attribute_name",
            "attributes__attribute_value",
        )

        return product


# ProductVariant
class ProductVariantDetailView(DetailView):
    model = ProductVariant
    slug_url_kwarg = "product_variant_slug"
    template_name = "products/product_variant_detail.html"
    context_object_name = "product_variant"

    def post(self, request, *args, **kwargs):
        nomenclature_code = request.POST.get("nomenclature_code")
        nomenclature = get_object_or_404(Nomenclature, code=nomenclature_code)
        cart, created = Cart.objects.get_or_create(user=request.user)
        cart_item, created = CartItem.objects.get_or_create(
            cart=cart, nomenclature=nomenclature
        )

        if not created:
            cart_item.quantity += 1
        cart_item.save()

        redirect_url = self.get_object().get_absolute_url()
        return redirect(redirect_url)

    def get_queryset(self):
        product_variant = ProductVariant.objects.select_related(
            "product",
            "product__brand",
            "product__subcategory",
            "product__category",
            "attributes__attribute_name",
            "attributes__attribute_value",
        ).prefetch_related(
            "product__attributes__attribute_name",
            "product__attributes__attribute_value",
        )

        color = self.request.GET.get("color")

        if color:
            product_variant = product_variant.filter(
                attributes__attribute_value__value=color
            )
        return product_variant


class ProductVariantListView(ListView):
    model = ProductVariant
    template_name = "products/product_variant_list.html"
    context_object_name = "product_variants"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # colors = cache.get("colors")
        # if not colors:
        #     colors = Attribute.objects.filter(
        #         attribute_name__name="color"
        #     ).select_related("attribute_value")
        #     cache.set("colors", colors, 3600)  # Кэш на 1 час
        colors = Attribute.objects.filter(attribute_name__name="color").select_related(
            "attribute_value"
        )

        properties = Attribute.objects.filter(
            attribute_name__name="properties"
        ).select_related("attribute_value")

        categories = Category.objects.all()
        subcategories = Subcategory.objects.all().prefetch_related("category")
        brands = Brand.objects.all()

        context["categories"] = categories
        context["subcategories"] = subcategories
        context["brands"] = brands
        context["colors"] = colors
        context["properties"] = properties

        context["selected_categories"] = self.request.GET.getlist("category")
        context["selected_subcategories"] = self.request.GET.getlist("subcategory")
        context["selected_brands"] = self.request.GET.getlist("brand")
        context["selected_colors"] = self.request.GET.getlist("color")
        context["selected_properties"] = self.request.GET.getlist("property")

        return context

    def get_queryset(self) -> QuerySet[Product]:
        queryset = ProductVariant.objects.all().select_related("product")
        queryset = queryset.prefetch_related(
            Prefetch(
                "attributes",
                queryset=Attribute.objects.select_related(
                    "attribute_name", "attribute_value"
                ),
            ),
            Prefetch(
                "product",
                queryset=Product.objects.select_related(
                    "brand", "category", "subcategory"
                ),
            ),
        )

        categories = self.request.GET.getlist("category")
        subcategories = self.request.GET.getlist("subcategory")
        brands = self.request.GET.getlist("brand")
        properties = self.request.GET.getlist("property")
        colors = self.request.GET.getlist("color")

        if categories:
            queryset = queryset.filter(product__category__name__in=categories)

        if subcategories:
            queryset = queryset.filter(product__subcategory__name__in=subcategories)

        if brands:
            queryset = queryset.filter(product__brand__name__in=brands)

        if properties:
            queryset = queryset.filter(
                product__attributes__attribute_value__value__in=properties,
            )

        if colors:
            queryset = queryset.filter(
                attributes__attribute_value__value__in=colors,
            ).distinct()

        return queryset

eshop/products/templates/products/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Fashion Fusion</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="{% static 'products/css/style.css' %}" type="text/css"/>
    <link type="image/x-icon" href="{% static 'products/icons/favicon.png' %}" rel="shortcut icon">
    <link type="Image/x-icon" href="{% static 'products/icons/favicon.png' %}" rel="icon">
</head>
<body>
    <div class="wrapper">
        <div class="content">
            <div class="menu">
                <div class="container">
                    <div class="menu__row">
                        <div class="menu__image">
                            <a href="{% url 'products:index' %}">
                                <img src="{% static 'products/img/company_logo.png' %}" alt="Company Logo">
                            </a>
                        </div>
                        <div class="menu__body">
                            <ul class="menu__list">
                                <li>
                                    <a href="{% url 'products:index' %}">Home</a>
                                </li>
                                <li>
                                    <a href="#">About</a>
                                </li>
                                <li>
                                    <a href="#">Services</a>
                                </li>
                                <li>
                                    <a href="#">Blog</a>
                                </li>
                                <li>
                                    <a href="#">Contacts</a>
                                </li>
                                {% if request.user.is_authenticated %}
                                <li>
                                    <a href="{% url 'orders:order_list' %}">My Orders</a>
                                </li>
                                <li>
                                    <a href="{% url 'users:profile' username=request.user.username %}">My Profile</a>
                                </li>
                                <li>
                                    <a href="{% url 'cart:cart_detail' %}">Cart</a>
                                </li>
                                {% endif %}
                                {% if not request.user.is_authenticated %}
                                <li>
                                    <a href="{% url 'users:registration' %}">Registration</a>
                                </li>
                                <li>
                                    <a href="{% url 'users:login' %}">Log In</a>
                                </li>
                                {% else %}
                                <li>
                                    <form class="menu__form" method="post" action="{% url 'users:logout' %}">
                                        {% csrf_token %}
                                        <!-- <button type="submit">Log Out</button> -->
                                        <button type="submit"><img src="{% static 'products/icons/logout.svg' %}" alt="" height="20"></button>
                                    </form>                         
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="nav">
                <div class="container">
                    <div class="nav__row">
                        <ul class="nav__list">
                            <li><a href="{% url 'products:product_variant_list' %}">All products</a></li>
                            <li><a href="{% url 'products:brand_list' %}">Brands</a></li>
                            <li><a href="{% url 'products:product_variant_list' %}?subcategory=t-shirt">T-shirt</a></li>
                            <li><a href="{% url 'products:product_variant_list' %}?subcategory=shirt">Shirt</a></li>
                            <li><a href="{% url 'products:product_variant_list' %}?subcategory=jacket">Jacket</a></li>
                            <li><a href="{% url 'products:product_variant_list' %}?subcategory=top">Top</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            
            {% block content %}
            {% endblock %}

        </div>
        <footer class="footer">
            <div class="container">
                <div class="footer__row">
                    <div class="footer_text">Fashion Fusion. All rights reserverd®</div>
                </div>
            </div>
        </footer>
    </div>
    <!-- Script for the 2nd option -->
    <!-- <script>
        function resetForm() {
            const form = document.getElementById('filterForm');
            form.querySelectorAll('input[type="checkbox"]').forEach(checkbox => checkbox.checked = false);
            // Optionally, submit the form if you want to refresh the page without filters
            form.submit();
        }
    </script> -->
    <!-- <script src="{% static 'products/js/product_variant.js' %}"></script> -->
</body>
</html>

eshop/products/templates/products/category_list.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}

    {% for categorie in categories %}

        {{ categorie }}

    {% endfor %}

{% endblock %}

eshop/products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}

<div class="subject">
    <div class="container">
        <div class="subject__row">
            <div class="subject__title">
                <h2>New Outwear Collection</h2>
            </div>
            <div class="subject__novelty">
                <div class="subject__link">
                    <a href="{% url 'products:product_variant_list' %}">Shop Now</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="categories-section">
    <div class="container">
        <div class="categories-section__row">
            <div class="categories-section__title">
                <h2>Categories</h2>
            </div>
            <div class="categories-sections__body">
                <div class="categories-section__columns">
                    <div class="categories-section__column">
                        <div class="categories-section__image">
                            <a class="link-overlay" href="{% url 'products:brand_list' %}">Brands</a>
                            <img src="../../static/products/img/categories_1.jpg" alt="">
                        </div>
                    </div>
                    <div class="categories-section__column">
                        <div class="categories-section__image">
                            <a class="link-overlay" href="{% url 'products:product_variant_list' %}">Products</a>
                            <img src="../../static/products/img/categories_4.jpg" alt="">
                        </div>
                    </div>
                    <div class="categories-section__column">
                        <div class="categories-section__image">
                            <a class="link-overlay" href="{% url 'products:product_variant_list' %}?category=gents">Gents</a>
                            <img src="../../static/products/img/categories_3.jpg" alt="">
                        </div>
                    </div>
                    <div class="categories-section__column">
                        <div class="categories-section__image">
                            <a class="link-overlay" href="{% url 'products:product_variant_list' %}?category=ladies">Ladies</a>
                            <img src="../../static/products/img/categories_2.jpg" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="advantage">
    <div class="container">
        <div class="advantage__row">
            <div class="advantage__title">
                <h2>Why Choose Us?</h2>
            </div>
            <div class="advanatage__body">
                <ul class="advanatage__list">
                    <li>
                        <img src="../../static/products/icons/support.svg" alt="Customer Support"><p>Customer Support</p>
                    </li>
                    <li>
                        <img src="../../static/products/icons/quality.svg" alt="Premium Quality"><p>Premium Quality</p>
                    </li>
                    <li>
                        <img src="../../static/products/icons/price_tag.svg" alt="Competitive Prices"><p>Competitive Prices</p>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

eshop/products/templates/products/product_variant_list.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}

<div class="product">
    <div class="container">
        <div class="product__row">
            <div class="product__filter">
                <div class="product__options">
                    <div class="product__search">
                        <form method="get" action="{% url 'products:product_variant_list' %}" id="filterForm">
                            <div class="product__category">
                                <h2>Categories</h2>
                                {% for category in categories %}
                                <div class="product__checkbox">
                                    <input type="checkbox" class="product__input" id="product__checkbox__category{{ category.id }}" name="category" value="{{ category.name }}" {% if category.name in selected_categories %}checked{% endif %}>
                                    <label class="product__checkbox__label" for="product__checkbox__category{{ category.id }}">{{ category.name.capitalize }}</label>
                                </div>
                                {% endfor %}
                            </div>
                            <div class="product__subcategories">
                                <h2>Subcategories</h2>
                                {% for subcategory in subcategories %}
                                <div class="product__checkbox">
                                    <input type="checkbox" class="product__input" id="product__checkbox__subcategory{{ subcategory.id }}" name="subcategory" value="{{ subcategory.name }}" {% if subcategory.name in selected_subcategories %}checked{% endif %}>
                                    <label class="product__checkbox__label" for="product__checkbox__subcategory{{ subcategory.id }}">{{ subcategory.name.capitalize }}</label>
                                </div>
                                {% endfor %}
                            </div>
                            <div class="product__properties">
                                <h2>Properties</h2>
                                {% for property in properties %}
                                <div class="product__checkbox">
                                    <input type="checkbox" class="product__input" id="product__checkbox__property{{ property.id }}" name="property" value="{{ property.attribute_value.value }}" {% if property.attribute_value.value in selected_properties %}checked{% endif %}>
                                    <label class="product__checkbox__label" for="product__checkbox__property{{ property.id }}">{{ property.attribute_value.value }}</label>
                                </div>
                                {% endfor %}
                            </div>
                            <div class="product__colors">
                                <h2>Colors</h2>
                                {% for color in colors %}
                                <div class="product__checkbox">
                                    <input type="checkbox" class="product__input" id="product__checkbox__color{{ color.id }}" name="color" value="{{ color.attribute_value.value }}" {% if color.attribute_value.value in selected_colors %}checked{% endif %}>
                                    <label class="product__checkbox__label" for="product__checkbox__color{{ color.id }}">{{ color.attribute_value.value }}</label>
                                </div>
                                {% endfor %}
                            </div>
                            <div class="product__brands">
                                <h2>Brands</h2>
                                {% for brand in brands %}
                                <div class="product__checkbox">
                                    <input type="checkbox" class="product__input" id="product__checkbox__brand{{ brand.name }}" name="brand" value="{{ brand.name }}" {% if brand.name in selected_brands %}checked{% endif %}>
                                    <label class="product__checkbox__label" for="product__checkbox__brand{{ brand.name }}">{{ brand.name }}</label>
                                </div>
                                {% endfor %}
                            </div>
                            <button class="product__submit__btn" type="submit">Search</button>
                            <!-- Option 1 -->
                            <button class="product__reset__btn" type="button" onclick="window.location.href='{% url 'products:product_variant_list' %}'">Reset</button>
                            <!-- Option 2 -->
                            <!-- <button class="product__reset__btn" type="button" onclick="resetForm()">Reset</button> -->
                        </form>
                    </div>
                </div>
            </div>
            <div class="product__list">
                {% for product_variant in product_variants %}
                <div class="product__info">
                    <div class="product__photo">
                        <img src="{{ product_variant.get_title_photo }}" alt="">
                    </div>
                    <div class="product__name">
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'products:product_variant' product_variant_slug=product_variant.slug %}?color={{ product_variant.attributes.attribute_value.value }}">{{ product_variant.product.name }} {{ product_variant.price }} €</a>
                        {% else %}
                        <a href="{% url 'products:product_variant' product_variant_slug=product_variant.slug %}?color={{ product_variant.attributes.attribute_value.value }}">{{ product_variant.product.name }}</a>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>            
        </div>
    </div>
</div>
{% endblock %}

eshop/products/templates/products/test.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'products/css/main.css' %}" type="text/css"/>
    <title>E-comm</title>
</head>
<body>
    <div class="page">
        <header>
            <nav>
                <ul class="nav-ul">
                    <li class="nav-li">
                        <a href="{% url 'products:index' %}">Home</a>
                    </li>
                    <li class="nav-li">
                        <a href="#">About Us</a>
                    </li>
                    <li class="nav-li">
                        <a href="#">Services</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-li">
                        <a href="{% url 'orders:order_list' %}">My Orders</a>
                    </li>
                    <li class="nav-li">
                        <a href="{% url 'users:profile' username=request.user.username %}">My Profile</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="test-ul">
                    {% if not request.user.is_authenticated %}
                    <li class="test-li">
                        <a href="{% url 'users:registration' %}">Registration</a>
                    </li>
                    <li class="test-li">
                        <a href="{% url 'users:login' %}">Login</a>
                    </li>
                    {% else %}
                    <li class="test-li">
                        <form method="post" action="{% url 'users:logout' %}">
                        {% csrf_token %}
                        <button type="submit">logout</button>
                        </form> 
                    </li>
                    {% endif %}
                </ul>

            </nav>
        </header>

        <main class="main">
            {% block content %}
            {% endblock %}
        </main>

        <footer class="footer">
            <p>All rights reserved</p>
        </footer>
    </div>
</body>
</html>