eshop/api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views


app_name = "api"
urlpatterns = [
    # Token
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    # AttributeName Objects
    path("attributename/", views.AttributeNameCreateAPIView.as_view()),
    path(
        "attributename/<int:pk>/", views.AttributeNameGetUpdateDestroyAPIView.as_view()
    ),
    path("attributenames/", views.AttributeNameListAPIView.as_view()),
    # AttributeValue Objects
    path("attributevalue/", views.AttributeValueCreateAPIView.as_view()),
    path(
        "attributevalue/<int:pk>/",
        views.AttributeValueGetUpdateDestroyAPIView.as_view(),
    ),
    path("attributevalues/", views.AttributeValueListAPIView.as_view()),
    # Attribute Objects
    path("attributes/", views.AttributeAPIViewSet.as_view({"get": "list"})),
    path("attribute/", views.AttributeCreateAPIView.as_view()),
    path(
        "attribute/<int:pk>/",
        views.AttributeAPIViewSet.as_view(
            {
                "get": "retrieve",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
    ),
    # Brand Objects
    path("brand/", views.BrandCreateAPIView.as_view()),
    path("brand/<int:pk>/", views.BrandGetUpdateDestroyAPIView.as_view()),
    path("brands/", views.BrandListAPIView.as_view()),
    # Product Objects
    path("product/", views.ProductCreateAPIView.as_view()),
    path("product/<int:pk>/", views.ProductGetUpdateDestroyAPIView.as_view()),
    path("products/", views.ProductListAPIView.as_view()),
    # Nomenclature Objects
    path("nomenclature/", views.NomenclatureCreateAPIView.as_view()),
    path("nomenclature/<int:pk>/", views.NomenclatureGetUpdateDestroyAPIView.as_view()),
    path("nomenclatures/", views.NomenclatureListAPIView.as_view()),
    # Image Objects
    path("image/", views.ImageCreateAPIView.as_view()),
    path("image/<int:pk>/", views.ImageGetUpdateDestroyAPIView.as_view()),
    path("images/", views.ImageListAPIView.as_view()),
    # ShippingAddress Objects
    path("shipping_address/", views.ShippingAddressCreateAPIView.as_view()),
    path(
        "shipping_address/<int:pk>/",
        views.ShippingAddressGetUpdateDestroyAPIView.as_view(),
    ),
    path("shipping_addresses/", views.ShippingAddressListAPIView.as_view()),
    # Order Objects
    path("order/", views.OrderCreateAPIView.as_view()),
    path("order/<int:pk>/", views.OrderGetUpdateDestroyAPIView.as_view()),
    path("orders/", views.OrderListAPIView.as_view()),
    # OrderItem Objects
    path("orderitem/", views.OrderItemCreateAPIView.as_view()),
    path("orderitem/<int:pk>/", views.OrderItemGetUpdateDestroyAPIView.as_view()),
    path("orderitems/", views.OrderItemListAPIView.as_view()),
    # Invoice Objects
    path("invoice/<int:pk>/", views.InvoiceDetailAPIView.as_view()),
    # Import
    path("import/", views.ImportAPIView.as_view()),
]

eshop/cart/urls.py
from django.urls import path
from .views import (
    CartDetailView,
    CheckoutView,
    OrderConfirmationView,
)

app_name = "cart"
urlpatterns = [
    path("my-cart/", CartDetailView.as_view(), name="cart_detail"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path(
        "order-confirmation/",
        OrderConfirmationView.as_view(),
        name="order_confirmation",
    ),
]

eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # Project paths
    path("admin/", admin.site.urls),
    path("api/v1/", include("api.urls")),
    path("", include("products.urls")),
    path("orders/", include("orders.urls")),
    path("users/", include("users.urls")),
    path("cart/", include("cart.urls")),
    # Swagger
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # import mimetypes

    # mimetypes.add_type("application/javascript", ".js", True)
    urlpatterns = [path("__debug__/", include("debug_toolbar.urls"))] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop/cart/models.py
from django.db import models
from django.contrib.auth.models import User

from products.models import Nomenclature
from orders.models import ShippingAddress


class Cart(models.Model):
    user = models.OneToOneField(User, related_name="cart", on_delete=models.CASCADE)
    shipping_address = models.OneToOneField(
        ShippingAddress, on_delete=models.CASCADE, related_name="cart", null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="cart_items")
    nomenclature = models.ForeignKey(Nomenclature, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def get_total_price(self):
        return self.quantity * self.nomenclature.price

eshop/cart/forms.py
from django import forms
from .models import CartItem


class CartItemForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = ["quantity"]
        widgets = {"quantity": forms.NumberInput(attrs={"min": "1"})}

eshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from django.views import View
from django.contrib import messages
from django.contrib.auth.models import User
from django.db import transaction


from .models import CartItem, Cart
from .forms import CartItemForm
from products.models import Nomenclature
from orders.models import Order, OrderItem, ShippingAddress


class CartDetailView(View):
    def get(self, request):
        cart = get_object_or_404(Cart, user=request.user)
        cart_items = cart.cart_items.all()
        for item in cart_items:
            if item.quantity == 0:
                item.delete()
        cart_item_forms = [
            (item, CartItemForm(instance=item, prefix=str(item.id)))
            for item in cart_items
        ]
        total_price = sum(item.get_total_price() for item in cart_items)
        return render(
            request,
            "cart/cart_detail.html",
            {
                "cart": cart,
                "cart_item_forms": cart_item_forms,
                "total_price": total_price,
                "addresses": request.user.shipping_addresses.filter(is_active=True),
            },
        )

    def post(self, request):
        cart = get_object_or_404(Cart, user=request.user)
        address = ShippingAddress.objects.get(id=request.POST.get("address_id"))
        cart.shipping_address = address
        cart.save()
        cart_items = cart.cart_items.all()
        form_errors = False

        for item in cart_items:
            form = CartItemForm(request.POST, instance=item, prefix=str(item.id))
            if form.is_valid():
                form.save()
            else:
                form_errors = True

        return redirect("cart:cart_detail")


class CheckoutView(View):
    def get(self, request):
        cart = Cart.objects.get(user=request.user)
        return render(request, "cart/checkout.html", {"cart": cart})

    def post(self, request):
        cart = Cart.objects.get(user=request.user)
        order = Order(user=request.user, shipping_address=cart.shipping_address)

        order_items = []

        with transaction.atomic():

            for item in cart.cart_items.all():
                nomenclature: Nomenclature = item.nomenclature

                if item.quantity <= nomenclature.quantity_available:
                    nomenclature.quantity_available -= item.quantity
                    order_item = OrderItem(
                        order=order, nomenclature=nomenclature, quantity=item.quantity
                    )
                    nomenclature.save()
                    order_items.append(order_item)

                else:
                    error_occurred = True
                    messages.error(
                        request,
                        f"Quantity for {nomenclature.product_variant.name} exceeds available stock.",
                    )
                    return redirect("cart:cart_detail")

            order.save()
            OrderItem.objects.bulk_create(order_items)

        cart.cart_items.all().delete()
        cart.shipping_address = None
        cart.save()
        return redirect("cart:order_confirmation")


class OrderConfirmationView(View):
    def get(self, request):
        return render(request, "cart/order_confirmation.html")

eshop/cart/templates/cart/cart_detail.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}

<div class="cart">
    <div class="container">
        <div class="cart__row">
            <div class="cart__title">
                <h2>Your Cart</h2>
            </div>
            <form method="post" action="{% url 'cart:cart_detail' %}">
                {% csrf_token %}
                <table>
                    <thead>
                        <tr>
                            <th>Product</th>
                            <th>Item Code</th>
                            <th>Item Price</th>
                            <th>Quantity</th>
                            <th>In Stock</th>
                            <th>Total Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item, form in cart_item_forms %}
                        <tr>
                            <td>{{ item.nomenclature.product_variant.name }}</td>
                            <td>{{ item.nomenclature.code }}</td>
                            <td>{{ item.nomenclature.price }}</td>
                            <td>{{ form.quantity }}</td>
                            <td>{{ item.nomenclature.quantity_available }}</td>
                            <td>{{ item.get_total_price }} €</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="cart__address">
                    {% if not cart.shipping_address %}
                    <div class="cart__current__address">
                        <p>Choose a delivery address</p>
                    </div>
                    {% else %}
                    <div class="cart__current__address">
                        <p>The order will be delivered to:</p>
                        <div class="cart__select__address"><p>{{ cart.shipping_address }}</p></div>
                    </div>
                    {% endif %}
                </div>
                <select class="address__select-box" name="address_id">
                    {% for address in addresses %}
                            <option value="{{ address.id }}">{{ address }}</option>
                    {% endfor %}
                </select>
                <button type="submit">Update Order</button>
            </form>
            <div class="cart__summary">
                <div class="cart__summary__total">
                    <p>Total Price: {{ total_price }} €</p>
                </div>
                {% if total_price > 0 and cart.shipping_address %}
                <div class="cart__summary__url">
                    <a href="{% url 'cart:checkout' %}">Proceed to Checkout</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

eshop/cart/templates/cart/checkout.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}
<div class="checkout-container">
    <h2>Checkout</h2>
    <form method="post" class="checkout-form">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">Name on Card:</label>
            <input type="text" id="name" name="name" required>
        </div>
        <div class="form-group">
            <label for="card-number">Card Number:</label>
            <input type="text" id="card-number" name="card-number" required>
        </div>
        <div class="form-group">
            <label for="expiry-date">Expiry Date:</label>
            <input type="text" id="expiry-date" name="expiry-date" placeholder="MM/YY" required>
        </div>
        <div class="form-group">
            <label for="cvv">CVV:</label>
            <input type="text" id="cvv" name="cvv" required>
        </div>
        <button type="submit" class="submit-btn">Confirm Order</button>
    </form>
</div>
{% endblock %}

eshop/cart/templates/cart/order_confirmation.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}
<div class="confirmation-container">
    <h2>Order Confirmed</h2>
    <p>Thank you for your order!</p>
</div>
{% endblock %}